## ---------------------------------------------------------------------------
##  分布式事务 配置文件
## ---------------------------------------------------------------------------
spring:
  application:
    name: shardingsphere

#分布式事务配置
omega:
  enabled: true
alpha:
  cluster:
    address: 127.0.0.1:8181
  feature:
    akka:
      enabled: true






